import type { Metadata } from "next";
import { Box } from "@chakra-ui/react";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers/provider";
import NavBar from "./components/header/header";
import Footer from "./components/footer/footer";
import { ChakraProviders } from "./providers/chakraProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body className={inter.className}>
        <ChakraProviders>
          <NavBar />
          <Providers>
            <Box minH={"70vh"} bg="#FAFCFF">
              {children}
            </Box>
          </Providers>
          <Footer />
        </ChakraProviders>
      </body>
    </html>
  );
}
